baseURL = 'http://vmsh.org/'
languageCode = 'en-us'
title = 'VMSH'
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

# disable dead links for now
#[[menu.main]]
#name = "Docs"
#url = "/docs/"
#weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[params.logo]
# Different logo for mobile needed?
mobile = "/images/vmsh.png"
standard  = "/images/vmsh.png"
